apiVersion: platform.example.org/v1beta1
kind: GrafanaStackConsumer
metadata:
  name: robk-telemetry-writer
  namespace: telemetry-consumers
spec:
  profile: robk-telemetry-writer
  stack:
    slug: robk
    region: prod-gb-south-1
