apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac/composition-rbac.yaml
  - provider/provider-grafana.yaml
  - function/install.yaml
  - apis/stack-v1beta1.yaml
  - apis/custom-role-binding-v1beta1.yaml
  - apis/access-v1beta1.yaml
  - apis/inventory-v1beta1.yaml
  - apis/fleet-v1beta1.yaml
  - apis/alerting-v1beta1.yaml
  - apis/agent-observability-v1beta1.yaml
  - apis/assistant-v1beta1.yaml
  - apis/datasource-access-v1beta1.yaml
  - apis/provisioning-v1beta1.yaml
  - apis/ladder-v1beta1.yaml
  - apis/k6-v1beta1.yaml
  - apis/synthetic-monitoring-v1beta1.yaml
  - apis/alerting-routing-v1beta1.yaml
  - apis/oncall-v1beta1.yaml
  - apis/cloud-integrations-v1beta1.yaml
  - apis/pdc-v1beta1.yaml
  - apis/service-accounts-v1beta1.yaml
  - apis/frontend-observability-v1beta1.yaml
  - apis/ml-v1beta1.yaml
  - apis/asserts-v1beta1.yaml
  - apis/stack-consumer-v1beta1.yaml
