apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://charts.crossplane.io/stable
      chart: crossplane
      targetRevision: 2.3.4
      helm:
        releaseName: crossplane
        valueFiles:
          - $values/deploy/crossplane/values.yaml
    - repoURL: https://github.com/rknightion/grafana-cloud-vending-machine
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
