apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-cloud-vending-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  destination:
    namespace: grafana-vending
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/rknightion/grafana-cloud-vending-machine
      targetRevision: main
      path: platform
    - repoURL: https://github.com/rknightion/grafana-cloud-vending-machine
      targetRevision: main
      path: deploy/aws
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 20
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
