apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-sso-example-oidc
  namespace: grafana-vending
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: grafana-vending-secrets
    kind: SecretStore
  target:
    name: grafana-sso-example-oidc
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: clientSecret
      remoteRef:
        key: /platform/grafana-cloud/profiles/example-oidc
        property: client_secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-incident-example-relay
  namespace: grafana-vending
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: grafana-vending-secrets
    kind: SecretStore
  target:
    name: grafana-incident-example-relay
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: authorization
      remoteRef:
        key: /platform/grafana-cloud/profiles/example-relay
        property: authorization
