apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: grafanaalertingroutings.platform.example.org
spec:
  scope: Namespaced
  group: platform.example.org
  names:
    kind: GrafanaAlertingRouting
    plural: grafanaalertingroutings
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              x-kubernetes-validations:
                - rule: "false"
                  message: This API is not implemented yet.
